### ISSUE TITLE
cpu - cpu version of gpu_specter should be fully correct

### ISSUE THREAD

**Issue by lastephey** [sbailey/gpu_specter#6]
This should likely be addressed after Issues #4 and #5 have been addressed.

Before transitioning the code from cpu to gpu, it should have uniform array and patch sizes and should be fully correct.

**Comment by dmargala** [comment]
@sbailey : I missed this in the PR review / code walkthrough of your recent refactor but it looks like there's a typo here (`results` should be `result`):

https://github.com/sbailey/gpu_specter/blob/7f60a4860e5e475668758fe599ac24ea86ce526e/bin/spex#L246-L249

Hopefully saves you some head scratching...
